# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'barcode.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1116, 805)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 3, 1121, 751))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.mainLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.mainLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.mainLayout.setContentsMargins(10, 10, 10, 0)
        self.mainLayout.setObjectName("mainLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit.setMaximumSize(QtCore.QSize(16777215, 40))
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.sityLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.sityLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.sityLabel.setObjectName("sityLabel")
        self.verticalLayout.addWidget(self.sityLabel)
        self.comboBoxSity = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBoxSity.setObjectName("comboBoxSity")
        self.verticalLayout.addWidget(self.comboBoxSity)
        self.eventLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.eventLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        self.eventLabel.setObjectName("eventLabel")
        self.verticalLayout.addWidget(self.eventLabel)
        self.buttonlyaout = QtWidgets.QHBoxLayout()
        self.buttonlyaout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.buttonlyaout.setContentsMargins(-1, -1, -1, 100)
        self.buttonlyaout.setSpacing(6)
        self.buttonlyaout.setObjectName("buttonlyaout")
        self.syncTicketButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.syncTicketButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.syncTicketButton.setObjectName("syncTicketButton")
        self.buttonlyaout.addWidget(self.syncTicketButton)
        self.comboBoxEvent = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBoxEvent.setObjectName("comboBoxEvent")
        self.buttonlyaout.addWidget(self.comboBoxEvent)
        self.verticalLayout.addLayout(self.buttonlyaout)
        self.yesLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.yesLabel.setFont(font)
        self.yesLabel.setObjectName("yesLabel")
        self.verticalLayout.addWidget(self.yesLabel)
        self.noLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.noLabel.setFont(font)
        self.noLabel.setAutoFillBackground(False)
        self.noLabel.setObjectName("noLabel")
        self.verticalLayout.addWidget(self.noLabel)
        self.mainLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableView = QtWidgets.QTableWidget(self.horizontalLayoutWidget)
        self.tableView.setObjectName("tableView")
        self.verticalLayout_2.addWidget(self.tableView)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.mainLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1116, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.tableView.setColumnCount(7)
        self.tableView.setSortingEnabled(True)
        self.tableView.setHorizontalHeaderLabels(
            ["cod_hs", "nom_bill_kn", "row", "place", "sector", "nom_res", "flag_check"])
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sityLabel.setText(_translate("MainWindow", "Город"))
        self.eventLabel.setText(_translate("MainWindow", "Мероприятие"))
        self.syncTicketButton.setText(_translate("MainWindow", "Sync"))
        self.yesLabel.setText(_translate("MainWindow", "TextLabel"))
        self.noLabel.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", ""))
        self.label_2.setText(_translate("MainWindow", ""))
        self.pushButton.setText(_translate("MainWindow", "Синхронизировать"))

